### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by nian1013** [pei-jikui/nginx-alg#19]
src/stream/ngx_stream_alg_module.c: In function ‘ngx_stream_alg_ftp_get_peer_addr’:
src/stream/ngx_stream_alg_module.c:75:23: error: variable ‘c’ set but not used [-Werror=unused-but-set-variable]
     ngx_connection_t *c;
                       ^
src/stream/ngx_stream_alg_module.c: In function ‘ngx_stream_alg_ftp_process_handler’:
src/stream/ngx_stream_alg_module.c:197:23: error: variable ‘c’ set but not used [-Werror=unused-but-set-variable]
     ngx_connection_t *c;
                       ^
cc1: all warnings being treated as errors
make[1]: *** [objs/src/stream/ngx_stream_alg_module.o] Error 1
make[1]: Leaving directory `/root/nginx-alg-1.0.1'
make: *** [build] Error 2

**Comment by pei-jikui** [comment]
Fixed and 1.0.2 is released for this. Thanks for the feedback.
